### ISSUE TITLE
How long does the token last?

### ISSUE THREAD

**Issue by TomasHubelbauer** [branchard/fast-speedtest-api#15]
Hi, I notice that the way to get the token is to take one from fast.com and use it. I want to run a speedtest nightly, I assume that just taking one now and using it for forever won't work. Is there any known expiration on the token? Do I need to first fetch one always and then run the speedtest?

**Comment by branchard** [comment]
I've noticed that the fast.com token rarely changes.

**Comment by zoobibackups** [comment]
> Hi, I notice that the way to get the token is to take one from fast.com and use it. I want to run a speedtest nightly, I assume that just taking one now and using it for forever won't work. Is there any known expiration on the token? Do I need to first fetch one always and then run the speedtest?

Is this free to use for unlimited requests
