### ISSUE TITLE
Failed to Fetch: CORS Policy problem

### ISSUE THREAD

**Issue by mark-lumbao** [branchard/fast-speedtest-api#19]
Here is the Error.

**Access to fetch at 'https://api.fast.com/netflix/speedtest?https=true&token=https://ipv4-c001-cgy001-globetelecom-isp.1.oca.nflxvideo.net/speedtest/range/0-0?%0A%20%20c=ph&n=132199&v=5&e=1588413106&t=gdamowYVB5mkSSmTJaaAgdxhJWo&urlCount=5' from origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.**

**Comment by amerikan** [comment]
Having a similar problem. For me it works fine when calling locally from my localhost, however, when it gets called from a https server that's when I get a CORS error.

**Comment by amostajo** [comment]
This is because the service is not meant to run outside fast.com, the library is a little hack coded to use their API without authorization, this most likely will not be fixable from the client-side.

**Comment by amerikan** [comment]
@amostajo you're absolutely right. I learned that the hard way.

**To future people running into this issue, read this:**
Anyone who's trying to use it on their website, this will **not** work in your typical setup. It only works on port 8000 (which is typically localhost and not your conventional port 80). Any other port you'll run into CORS issue. So yes, as @amostajo mentions don't rely on to serve actual websites or webapps.

**Comment by mark-lumbao** [comment]
Oh okay understood. Seems like there's nothing more to discuss. Thanks, everyone.
